"""One-shot data copy: SQLite -> PostgreSQL using streamed COPY.

Uses psycopg's `cursor.copy()` so 1M+ fingerprint rows go through STDIN in
chunks instead of being materialised in Python memory. Avoided the 1.9 GiB
OOM-thrash that executemany + fetchall hit on the small Lightsail box.

Assumes:
  * Postgres `trimbrain` DB exists and `schema_pg.sql` has been applied.
  * Target tables are empty (we don't dedup; pre-TRUNCATE if re-running).
"""
import json
import sqlite3
from datetime import datetime, timezone

import psycopg

SRC_DB = "/opt/trimbrain/trimbrain.db"
DSN = "dbname=trimbrain user=trimbrain"
CHUNK = 50_000

# Parent → children order so FK references resolve.
TABLES = [
    "episodes",
    "audio_files",
    "fingerprints",
    "jobs",
    "raw_matches",
    "canonical_segments",
    "episode_segments",
    "fingerprint_log",
    "match_log",
    "transcript_segments",
    "podcast_feed_meta",
    "client_events",
]

JSON_COLUMNS = {
    ("jobs", "episode_urls"),
    ("canonical_segments", "promoting_match_ids"),
    ("match_log", "raw_offset_candidates"),
}

BOOL_COLUMNS = {
    ("audio_files", "processing_complete"),
    ("episode_segments", "boundary_refined"),
}

TS_COLUMNS = {
    ("episodes", "created_at"),
    ("audio_files", "downloaded_at"),
    ("audio_files", "last_accessed_at"),
    ("jobs", "created_at"),
    ("jobs", "completed_at"),
    ("raw_matches", "detected_at"),
    ("canonical_segments", "first_seen_at"),
    ("canonical_segments", "last_seen_at"),
    ("fingerprint_log", "fingerprinted_at"),
    ("match_log", "run_at"),
    ("transcript_segments", "detected_at"),
    ("podcast_feed_meta", "updated_at"),
}

# Tables whose id column is GENERATED ALWAYS AS IDENTITY; we need OVERRIDING
# SYSTEM VALUE on COPY.
HAS_IDENTITY = {
    "episodes", "audio_files", "raw_matches", "canonical_segments",
    "episode_segments", "fingerprint_log", "match_log",
    "transcript_segments", "client_events",
}


def coerce(table: str, col: str, value):
    if value is None:
        return None
    if (table, col) in JSON_COLUMNS:
        if isinstance(value, str):
            try:
                return psycopg.types.json.Jsonb(json.loads(value))
            except json.JSONDecodeError:
                return None
        return psycopg.types.json.Jsonb(value)
    if (table, col) in BOOL_COLUMNS:
        return bool(value)
    if (table, col) in TS_COLUMNS:
        if isinstance(value, str):
            return datetime.fromisoformat(value).replace(tzinfo=timezone.utc)
        return value
    return value


def migrate_table(src: sqlite3.Connection, dst: psycopg.Connection, table: str) -> int:
    # Migration-time filtering: only copy fingerprints belonging to episodes
    # that have at least one episode_segment. Fingerprints for no-segment
    # episodes are dead weight (cleanup_episode_fingerprints_if_no_segments
    # would delete them anyway). Filter here so we don't pay the COPY cost.
    if table == "fingerprints":
        select_sql = (
            "SELECT * FROM fingerprints "
            "WHERE episode_id IN (SELECT DISTINCT episode_id FROM episode_segments)"
        )
    else:
        select_sql = f"SELECT * FROM {table}"
    cur_src = src.execute(select_sql)
    cols = [c[0] for c in cur_src.description]
    # Quote every column name so reserved words (e.g. transcript_segments.end)
    # don't trip the COPY parser. Identity columns are GENERATED BY DEFAULT so
    # explicit ids are accepted (PG 14 COPY can't take OVERRIDING).
    col_list = ", ".join(f'"{c}"' for c in cols)
    copy_sql = f"COPY {table} ({col_list}) FROM STDIN"

    total = 0
    with dst.cursor() as cur_dst:
        with cur_dst.copy(copy_sql) as copy:
            while True:
                rows = cur_src.fetchmany(CHUNK)
                if not rows:
                    break
                for row in rows:
                    copy.write_row(tuple(coerce(table, col, row[i]) for i, col in enumerate(cols)))
                total += len(rows)
    dst.commit()
    return total


def reset_sequences(dst: psycopg.Connection):
    """Advance IDENTITY sequences past max(id) so future inserts don't collide."""
    with dst.cursor() as cur:
        for t in HAS_IDENTITY:
            cur.execute(
                f"SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                f"COALESCE((SELECT MAX(id) FROM {t}), 0) + 1, false)",
                [t],
            )
    dst.commit()


def main():
    src = sqlite3.connect(f"file:{SRC_DB}?mode=ro", uri=True)
    src.row_factory = sqlite3.Row
    dst = psycopg.connect(DSN)

    print("Migrating tables (COPY-streamed):")
    grand = 0
    for table in TABLES:
        n = migrate_table(src, dst, table)
        print(f"  {table}: {n}", flush=True)
        grand += n

    print(f"Total: {grand} rows", flush=True)
    print("Resetting sequences...", flush=True)
    reset_sequences(dst)
    dst.close()
    src.close()
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
