-- TrimBrain schema, PostgreSQL 16 port (Phase 1).
--
-- Hand-written translation of the SQLite schema in /opt/trimbrain/trimbrain.db.
-- Goals of the port:
--   * Replace SQLite-isms (TEXT-for-everything, INTEGER-for-bool, JSON-in-TEXT)
--     with proper Postgres types so the query planner and validation can do
--     their job.
--   * Keep table and column names identical so the application diff is purely
--     in the driver / call-style layer, not in SQL strings.
--   * Match current FK behaviour (no cascades) so pgloader doesn't surface
--     pre-existing orphans during data migration. Adding cascades is a
--     follow-up, decided after the orphan audit.
--
-- Conventions:
--   BIGINT GENERATED BY DEFAULT AS IDENTITY replaces  INTEGER PRIMARY KEY AUTOINCREMENT
--     (BY DEFAULT chosen so bulk loaders / future migrations can set ids
--      explicitly without OVERRIDING SYSTEM VALUE, which PG 14 COPY doesn't
--      support anyway.)
--   TIMESTAMPTZ DEFAULT NOW()               replaces  TEXT DEFAULT (datetime('now'))
--   BIGINT (unix-ms)                        kept       for client_events.client_ts/received_at
--   BOOLEAN                                 replaces  INTEGER NOT NULL DEFAULT 0  (used as flag)
--   JSONB                                   replaces  TEXT  for known-JSON columns
--   DOUBLE PRECISION                        replaces  REAL
--
-- Run order: this file is idempotent (CREATE ... IF NOT EXISTS / CREATE INDEX IF NOT EXISTS).

BEGIN;

-- ---------------------------------------------------------------------------
-- Core: episodes (parent for nearly everything else)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS episodes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url              TEXT NOT NULL UNIQUE,
    guid             TEXT,
    title            TEXT,
    podcast_title    TEXT,
    podcast_id       TEXT,
    published        TEXT,                 -- left as TEXT; mixed feed formats in current data
    duration_seconds DOUBLE PRECISION,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Partial unique index: a guid is only unique within a podcast, and many rows
-- have guid IS NULL (pre-2026 imports). Matches SQLite's
-- idx_episodes_guid_podcast WHERE guid IS NOT NULL.
CREATE UNIQUE INDEX IF NOT EXISTS idx_episodes_guid_podcast
    ON episodes (guid, podcast_id)
    WHERE guid IS NOT NULL;

-- ---------------------------------------------------------------------------
-- audio_files: cached MP3s. One row per episode (UNIQUE episode_id).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audio_files (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id           BIGINT NOT NULL UNIQUE REFERENCES episodes(id),
    local_path           TEXT NOT NULL,
    size_bytes           BIGINT,
    download_ms          INTEGER,
    downloaded_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_accessed_at     TIMESTAMPTZ,
    processing_complete  BOOLEAN NOT NULL DEFAULT FALSE
);
-- Note: idx_audio_files_episode is redundant with UNIQUE(episode_id) in pg, omitted.

-- ---------------------------------------------------------------------------
-- fingerprints: stores audio hashes for episodes that produced segments.
-- After the 2026-05-12 cleanup the live table holds ~1M rows / ~120 MB, not
-- the 60–110M earlier estimate. The bloat came from never-pruned no-segment
-- episodes; analyze_full_feed_task now deletes those at job completion.
--
-- No surrogate PK in SQLite — kept that way to avoid an unused identity column.
-- The (episode_id, hash) and (hash) indexes serve lookups.
--
-- Partitioning is NOT needed at current scale. The table grows by ~1–5K rows
-- per analyzed episode (segment windows only, ~30s × 15 fp/s × few segments).
-- Even with 10× growth in podcasts catalogued, we stay well under the 10M-row
-- threshold where partitioning starts paying off. Revisit if EXPLAIN ANALYZE
-- on get_hash_similar_episodes shows the (hash) B-tree as a bottleneck.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fingerprints (
    episode_id BIGINT NOT NULL REFERENCES episodes(id),
    hash       BIGINT NOT NULL,
    timestamp  DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fp_episode  ON fingerprints (episode_id);
CREATE INDEX IF NOT EXISTS idx_fp_hash     ON fingerprints (hash);
CREATE INDEX IF NOT EXISTS idx_fp_hash_ep  ON fingerprints (hash, episode_id);
-- Optional add-on for the planner: BRIN on (episode_id) is ~1/1000th the size
-- of B-tree and almost as fast for the seq-scan-with-skip pattern that
-- get_hash_similar_episodes uses. Add only if EXPLAIN shows the B-tree is hot.
-- CREATE INDEX IF NOT EXISTS idx_fp_episode_brin ON fingerprints USING BRIN (episode_id);

-- ---------------------------------------------------------------------------
-- jobs: orchestration state for /analyze
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    id           TEXT PRIMARY KEY,        -- caller-supplied UUID
    status       TEXT NOT NULL DEFAULT 'running',  -- pending|running|done|error
    podcast_id   TEXT,
    episode_urls JSONB NOT NULL DEFAULT '[]'::jsonb,  -- was TEXT DEFAULT '[]'
    message      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    worker_pid   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs (status);
-- Useful for the init_db orphan-cleanup query that filters running jobs:
CREATE INDEX IF NOT EXISTS idx_jobs_status_worker
    ON jobs (status) WHERE worker_pid IS NULL;

-- ---------------------------------------------------------------------------
-- raw_matches: pairwise audio matches between two episodes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_matches (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ep_a_id      BIGINT NOT NULL REFERENCES episodes(id),
    ep_b_id      BIGINT NOT NULL REFERENCES episodes(id),
    start_a      DOUBLE PRECISION NOT NULL,
    end_a        DOUBLE PRECISION NOT NULL,
    start_b      DOUBLE PRECISION NOT NULL,
    end_b        DOUBLE PRECISION NOT NULL,
    offset_sec   DOUBLE PRECISION,
    confidence   DOUBLE PRECISION,
    hash_count   INTEGER,
    segment_type TEXT,
    detected_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_rm_ep_a ON raw_matches (ep_a_id);
CREATE INDEX IF NOT EXISTS idx_rm_ep_b ON raw_matches (ep_b_id);

-- ---------------------------------------------------------------------------
-- canonical_segments: a deduplicated segment definition (one row per
-- intro/outro/ad recognised across a podcast feed).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS canonical_segments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    podcast_id          TEXT NOT NULL,
    ref_episode_id      BIGINT NOT NULL REFERENCES episodes(id),
    ref_start           DOUBLE PRECISION NOT NULL,
    ref_end             DOUBLE PRECISION NOT NULL,
    segment_type        TEXT NOT NULL,  -- 'intro' | 'outro' | 'ad'
    episode_count       INTEGER NOT NULL DEFAULT 0,
    avg_confidence      DOUBLE PRECISION,
    min_confidence      DOUBLE PRECISION,
    first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    promoting_match_ids JSONB           -- was TEXT containing a JSON array of raw_match ids
);
CREATE INDEX IF NOT EXISTS idx_cs_podcast ON canonical_segments (podcast_id);
CREATE INDEX IF NOT EXISTS idx_cs_type    ON canonical_segments (segment_type);

-- ---------------------------------------------------------------------------
-- episode_segments: per-episode occurrence of a canonical segment.
-- This is what /segments serves to the mobile client.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS episode_segments (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id                 BIGINT NOT NULL REFERENCES episodes(id),
    canonical_segment_id       BIGINT NOT NULL REFERENCES canonical_segments(id),
    local_start                DOUBLE PRECISION NOT NULL,
    local_end                  DOUBLE PRECISION NOT NULL,
    confidence                 DOUBLE PRECISION,
    hash_count                 INTEGER,
    raw_match_id               BIGINT REFERENCES raw_matches(id),
    matched_against_episode_id BIGINT REFERENCES episodes(id),
    boundary_refined           BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_es_episode   ON episode_segments (episode_id);
CREATE INDEX IF NOT EXISTS idx_es_canonical ON episode_segments (canonical_segment_id);

-- ---------------------------------------------------------------------------
-- Telemetry: fingerprint_log / match_log (debugging + perf tracking)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fingerprint_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id       BIGINT NOT NULL REFERENCES episodes(id),
    hash_count       INTEGER,
    duration_sec     DOUBLE PRECISION,
    cpu_time_ms      INTEGER,
    fingerprinted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS match_log (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ep_a_id               BIGINT NOT NULL REFERENCES episodes(id),
    ep_b_id               BIGINT NOT NULL REFERENCES episodes(id),
    raw_offset_candidates JSONB,            -- was TEXT containing a JSON array
    raw_segment_count     INTEGER,
    final_segment_count   INTEGER,
    cpu_time_ms           INTEGER,
    run_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- transcript_segments: alternative pipeline (Whisper-based)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transcript_segments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id   BIGINT NOT NULL REFERENCES episodes(id),
    start        DOUBLE PRECISION NOT NULL,
    "end"        DOUBLE PRECISION NOT NULL,  -- 'end' is reserved-ish in pg; quote to match SQLite name
    segment_type TEXT NOT NULL,
    confidence   DOUBLE PRECISION,
    excerpt      TEXT,
    source       TEXT NOT NULL DEFAULT 'transcript',
    detected_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ts_episode ON transcript_segments (episode_id);

-- ---------------------------------------------------------------------------
-- podcast_feed_meta: per-podcast progress / algorithm-version tracking
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS podcast_feed_meta (
    podcast_id         TEXT PRIMARY KEY,
    feed_episode_count INTEGER,
    algorithm_version  TEXT,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- client_events: aggregated user telemetry (skip hits/misses uploaded from
-- mobile). Local rows are never deleted on-device; backend dedupes here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       TEXT NOT NULL,
    client_event_id BIGINT NOT NULL,         -- caller's local row id (per-client monotonic)
    skip_type       TEXT NOT NULL,           -- intro | ad | outro | miss
    duration_ms     INTEGER NOT NULL,
    episode_guid    TEXT,
    episode_url     TEXT,
    podcast_rss     TEXT,
    client_ts       BIGINT NOT NULL,         -- unix ms from client clock
    received_at     BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
    UNIQUE (client_id, client_event_id)
);
CREATE INDEX IF NOT EXISTS idx_client_events_skip_type ON client_events (skip_type);
CREATE INDEX IF NOT EXISTS idx_client_events_client_ts ON client_events (client_ts);
-- For per-podcast aggregation:
CREATE INDEX IF NOT EXISTS idx_client_events_rss ON client_events (podcast_rss);

COMMIT;

-- ---------------------------------------------------------------------------
-- After pgloader copies data, run this to align identity sequences with the
-- max(id) of each table. pgloader's "reset sequences" should do it, but verify.
-- ---------------------------------------------------------------------------
-- SELECT setval(pg_get_serial_sequence('episodes', 'id'),           COALESCE((SELECT MAX(id) FROM episodes), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('audio_files', 'id'),        COALESCE((SELECT MAX(id) FROM audio_files), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('raw_matches', 'id'),        COALESCE((SELECT MAX(id) FROM raw_matches), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('canonical_segments', 'id'), COALESCE((SELECT MAX(id) FROM canonical_segments), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('episode_segments', 'id'),   COALESCE((SELECT MAX(id) FROM episode_segments), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('fingerprint_log', 'id'),    COALESCE((SELECT MAX(id) FROM fingerprint_log), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('match_log', 'id'),          COALESCE((SELECT MAX(id) FROM match_log), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('transcript_segments', 'id'),COALESCE((SELECT MAX(id) FROM transcript_segments), 0) + 1, false);
-- SELECT setval(pg_get_serial_sequence('client_events', 'id'),      COALESCE((SELECT MAX(id) FROM client_events), 0) + 1, false);
